from game.utils.Vector import Vector

PLAYER_SPRITE_WIDTH = 64
PLAYER_SPRITE_HEIGHT = 64
PLAYER_MOVE_TOP = Vector(1, 8)
PLAYER_MOVE_LEFT = Vector(1, 9)
PLAYER_MOVE_BOTTOM = Vector(1, 10)
PLAYER_MOVE_RIGHT = Vector(1, 11)
PLAYER_MOVE_TILES_NUMBER = 8
PLAYER_MOVE_TIME = 70
PLAYER_STANDBY = Vector(1, 10)
PLAYER_WIDTH = 48
PLAYER_HEIGHT = 50

WINDOW_WIDTH = 1408
WINDOW_HEIGHT = 832